version: '2'
services:
  elasticsearch62:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata62:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.1
    environment:
       - ELASTICSEARCH_URL=http://elasticsearch62:9200
       - service.host="0.0.0.0"
    depends_on:
       - elasticsearch62
    ports:
       - 5601:5601
    networks:
       - esnet

volumes:
  esdata62:
    driver: local

networks:
  esnet:
